services:
  - type: web
    name: yh-time-reporting
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DEBUG
        value: "False"
      - key: CSRF_TRUSTED_ORIGINS
        value: https://yh-time-reporting.onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: SENDGRID_API_KEY
        value: ""
