LoadModule wsgi_module     libexec/httpd/mod_wsgi.so
WSGIScriptAlias / /webroot/yh_forms/wsgi.py

# create new
WSGIDaemonProcess yh_forms processes=2 threads=15 display-name=%{GROUP} home=/webroot python-path=/webroot:/webroot/yh_forms:/usr/lib/python3.9/site-packages:/usr/lib64/python3.9/site-packages:/usr/local/lib64/python3.9/site-packages
WSGIProcessGroup yh_forms
WSGIApplicationGroup %{GLOBAL}



Alias /media/ /webroot/media/
Alias /static/ /webroot/static/

LogLevel info