ServerRoot "/etc/httpd"

Listen 8080
ProxyRequests off

Include conf.modules.d/*.conf
User apache
Group apache
ServerName ${DOMAIN_NAME}
UseCanonicalName  On
UseCanonicalPhysicalPort off

# When this is on, there are vagrant issues
EnableSendfile off

IncludeOptional conf.d/*.conf
AddDefaultCharset UTF-8
# Protocols h2

  DocumentRoot /webroot


<Directory />
  AllowOverride none
  Require all denied
</Directory>

<Directory "/webroot">
  AllowOverride ALL
  # Allow open access:
  Require all granted
  Options -Indexes +FollowSymLinks
  DirectoryIndex index.php index.htm index.html
  DirectorySlash Off
  DirectoryIndexRedirect Off
  DirectoryCheckHandler Off
</Directory>

<Files ".ht*">
  Require all denied
</Files>

# Use separate instance for php-fpm
# Hack to test if env var PHP_FPM_HOST is definded by user 

Define "Test${PHP_FPM_HOST}"
<IfDefine !Testnotfpm>
ProxyPassMatch ^/(.*\.php)$ fcgi://${PHP_FPM_HOST}:9000/webroot/$1
</IfDefine>

# Secure dot files
<FilesMatch "^\.">
  Require all denied
</FilesMatch>

# Secure dot folders
<DirectoryMatch "^\.|\/\.">
  Require all denied
</DirectoryMatch>

# Secure named files
<FilesMatch "docker-compose.yml|Dockerfile|Gemfile.*|phpunit.xml|Rakefile|README.*|Runfile|composer.*|unit.php">
  Require all denied
</FilesMatch>

  ErrorLog /dev/stderr
#  TransferLog /dev/stdout

RemoteIPHeader X-Forwarded-For
## RemoteIPTrustedProxy

## Load Modules
# LoadModule mpm_prefork_module modules/mod_mpm_prefork.so
LoadModule mpm_event_module modules/mod_mpm_event.so
# LoadModule mpm_worker_module modules/mod_mpm_worker.so
# LoadModule php_module modules/libphp.so

<IfModule log_config_module>
  <IfModule logio_module>
    # You need to enable mod_logio.c to use %I and %O
    LogFormat "%a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
  </IfModule>
  CustomLog /dev/stdout combinedio
</IfModule>

<IfModule alias_module>
  ScriptAlias /cgi-bin/ "/var/www/cgi-bin/"
</IfModule>

<IfModule mime_module>
  TypesConfig /etc/mime.types
  AddType application/x-compress .Z
  AddType application/x-gzip .gz .tgz
  AddType text/html .shtml
  AddOutputFilter INCLUDES .shtml
</IfModule>

<IfModule mime_magic_module>
  MIMEMagicFile conf/magic
</IfModule>

<IfModule mpm_prefork_module>
    StartServers              10
    ServerLimit               500
    MinSpareServers           5
    MaxSpareServers           50
    MaxRequestWorkers         500
    MaxConnectionsPerChild    0
</IfModule>

# XSS Protection
# Reference: https://github.com/h5bp/server-configs-apache/blob/master/src/security/x-xss-protection.conf
<IfModule mod_headers.c>
  Header set X-XSS-Protection "1; mode=block"
  <FilesMatch "\.(appcache|atom|bbaw|bmp|crx|css|cur|eot|f4[abpv]|flv|geojson|gif|htc|ico|jpe?g|js|json(ld)?|m4[av]|manifest|map|markdown|md|mp4|oex|og[agv]|opus|otf|pdf|png|rdf|rss|safariextz|svgz?|swf|topojson|tt[cf]|txt|vcard|vcf|vtt|webapp|web[mp]|webmanifest|woff2?|xloc|xml|xpi)$">
    Header unset X-XSS-Protection
  </FilesMatch>
</IfModule>
