Listen 8443 https
<VirtualHost _default_:8443>
    SSLEngine on
    SSLCertificateFile /etc/pki/tls/certs/cert.crt
    SSLCertificateKeyFile /etc/pki/tls/private/ca.key
    SSLCertificateChainFile /etc/pki/tls/certs/chainfile.crt
</VirtualHost>