# Generated by Django 4.1 on 2023-03-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_yhform_comments_alter_yhform_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yhform',
            name='comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
